#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM ubuntu

COPY ServerBuild/ /ServerBuild/

CMD /ServerBuild/server.x86_64
